#include<stdio.h>
main()
{
    int i,j;
    for(i=1;i<=4;i++)
    {
        for(j=1;j<=i;j++)
        {
            if(i==1)
            {
                printf("1");
            }
            else
            {
                if(i%2==0)
                {
                    if(j%2==0)
                        printf("1");
                        else
                            printf("0");
                }
                else
                {
                    if(j%2==0)
                        printf("0");
                    else
                        printf("1");
                }
            }
        }
        printf("\n");
    }
}

